use jar bundler if found

diff --git a/bin/cbundler b/bin/cbundler
--- a/bin/cbundler
+++ b/bin/cbundler
@@ -30,15 +30,40 @@ if [ -z "${APP_BASE}" ] ; then
 fi
 APP_BASE=$(cd ${APP_BASE} && pwd)
 
-# Run bundler
-cd ${SCRIPT_BASE}/../appstore-common && \
-MAVEN_OPTS="${debug} ${MAVEN_OPTS}" mvn exec:java \
-  -Dexec.mainClass=cloudos.appstore.bundler.MultiBundlerMain \
-  -Dexec.args="${APP_BASE}" \
-  1>&2
-if [ $? -ne 0 ] ; then
-  die "Error running multi-bundler on ${APP_BASE}"
+# Find bundler jar.
+BUNDLER_JAR="not-found"
+if [ -f ${SCRIPT_BASE}/../packages/cloudos-app-bundler.jar ] ; then
+  BUNDLER_JAR="${SCRIPT_BASE}/../packages/cloudos-app-bundler.jar"
+
+elif [ -f ${SCRIPT_BASE}/../appstore-common/pom.xml ] ; then
+  # Run from cloudos-appstore/bin, use maven directly
+  BUNDLER_JAR="use-maven"
 fi
+
+
+case "${BUNDLER_JAR}" in
+  not-found)
+    die "Multi-bundler jar could not be located"
+  ;;
+
+  use-maven)
+    echo 1>&2 "Running maven multi-bundler with options: ${APP_BASE}"
+    cd ${SCRIPT_BASE}/../appstore-common && \
+    MAVEN_OPTS="${debug} ${MAVEN_OPTS}" mvn exec:java \
+      -Dexec.mainClass=cloudos.appstore.bundler.MultiBundlerMain \
+      -Dexec.args="${APP_BASE}" \
+      1>&2
+    if [ $? -ne 0 ] ; then
+      die "Error running multi-bundler on ${APP_BASE}"
+    fi
+  ;;
+
+  *)
+    # we have a jar file, use it
+    echo 1>&2 "Running jar multi-bundler with options: ${APP_BASE}"
+    java ${debug} -cp ${BUNDLER_JAR} cloudos.appstore.bundler.MultiBundlerMain ${APP_BASE}
+  ;;
+esac
 
 # Print names of app bundle tarballs
 find $(find ${APP_BASE} -type d -name target) -type f -name "*-bundle.tar.gz"
